FORMAT: 1A
HOST: http://www.Connecus.info

# ConnecUsApi MyCliques
ConnecUs API is a *personal link saving* service, that is used to save important links that connect the world to your stuff.

# Group Cliques
Cliques related resources of the **Cliques API**

## Cliques Collection [/cliques]
### List all Cliques [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "MySite"
        }, {
          "id": 2, "title": "MyFavSite"
        }]

### Create a Clique [POST]
+ Request (application/json)

        { "title": "Good Site for learning" }

+ Response 201 (application/json)

        { "id": 3, "title": "Good Site for learning." }

## Clique [/cliques/{id}]
A single Clique object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Clique to perform action with. Has example value.

### Retrieve a Clique [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "MyFavSite2" }

### Remove a Clique [DELETE]
+ Response 204
